-- Problem 2: Even Fibonacci Numbers
-- Each new term in the Fibonacci sequence is generated byadding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

fibonacci :: Int -> Int
fibonacci limit = fibonacci' 1 2 limit 0

fibonacci' :: Int -> Int -> Int -> Int -> Int
fibonacci' first second limit sum | second > limit = sum
                                  | (second `mod` 2) == 0 = fibonacci' second (first + second) limit (sum + second)
                                  | otherwise = fibonacci' second (first + second) limit (sum)

